--test block
local Matrix = require("matrix")

time1 = os.clock()
math.randomseed(os.clock())
mat1 = Matrix:create(400, 400, 1)
mat2 = Matrix:create(400, 10, 3)
print("mat1 size:", mat1:getSize())
print("mat2 size:", mat2:getSize())
print("mat1")
--mat1:display()
print()
print("mat2")
--mat2:display()
--test add method
--mat3 = mat1:add(mat2)
print()
print("MAt3")
--mat3:display()
time2 = os.clock()
print(time2 - time1)
--test mul method
time3 = os.time()
local mat4 = mat1:mul(mat2)
time4 = os.time()

print()
print("mat4")
print("mat4 size: ", mat4:getSize())
print(time4 - time3)
--mat4:display() 